[package]
name = "benchmark"
version = "0.1.0"
authors = ["Xavier Lau <c.estlavie@icloud.com>"]

[dependencies]
time = "*"

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = false
