[package]
name = "n-queens"
version = "0.1.0"
authors = ["Aurevoir Xavier <c.estlavie@icloud.com>"]

[dependencies]
time = "*"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[profile.test]
opt-level = 3

[profile.bench]
opt-level = 3